"""fix_refresh_token_expires_at

Revision ID: 68bf88cadf2b
Revises: 1737d3e08d9e
Create Date: 2026-03-15 21:07:24.129745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68bf88cadf2b'
down_revision: Union[str, None] = '1737d3e08d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
